name: R-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          extra-packages: |
            any::pkgload
            any::roxygen2
            any::testthat

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Run tests
        run: |
          pkgload::load_all(".", export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)
          testthat::test_local(".", reporter = "summary")
        shell: Rscript {0}
